#!/bin/sh -e

dbus-uuidgen --ensure=/etc/machine-id

addgroup -S messagebus || true
adduser -SDHh /dev/null -s /usr/bin/nologin -G messagebus -g messagebus messagebus || true

chown root:messagebus /usr/libexec/dbus-daemon-launch-helper
chmod 4750            /usr/libexec/dbus-daemon-launch-helper
