#!/bin/sh -e

Ensure we have a machine ID.
exec dbus-uuidgen --ensure=/etc/machine-id

addgroup -S messagebus 2>/dev/null
adduser -S -D -H -h /dev/null -s /usr/bin/nologin -G messagebus -g messagebus messagebus 2>/dev/null

chown root:messagebus /usr/libexec/dbus-daemon-launch-helper
chmod 4750            /usr/libexec/dbus-daemon-launch-helper
