#!/bin/sh -e

export DESTDIR="$1"

rm -rf po

sed -i '/^find_package(KF5DocTools/d' CMakeLists.txt
sed -i '/add_subdirectory(docs)/d'    CMakeLists.txt
sed -i '/^find_package(DocBookXML/d'  src/CMakeLists.txt

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTING=NO \
    -Wno-dev -G Ninja

ninja -C build
ninja -C build install

# These files are both made post build so we remove the 
# DocTools reference here
sed -i '/^find_dependency(KF5Doc/d' \
    "$1/usr/lib/cmake/KF5KDELibs4Support/KF5KDELibs4SupportConfig.cmake"
sed -i '/^include("${KF5Doc/d' \
    "$1/usr/lib/cmake/KF5KDELibs4Support/KDE4Macros.cmake"
