#!/bin/sh -e

export DESTDIR="$1"

rm -rf po

patch -p1 < remove-doctool.patch

sed -i '/^find_package(KF5DocTools/d' CMakeLists.txt
sed -i '/add_subdirectory(docs)/d'    CMakeLists.txt

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTING=NO \
    -Wno-dev -G Ninja

ninja -C build
ninja -C build install
