#!/bin/sh -e

export DESTDIR="$1"

rm -rf doc

sed -i 's/DocTools//'              CMakeLists.txt
sed -i '/add_subdirectory(doc)/d'  CMakeLists.txt
sed -i '/kdoctools_install(po)/d'  CMakeLists.txt
#sed -i 's/--mode=go=rX,u+rw,a-s//' kdevplatform/cmake/modules/KDevPlatformMacros.cmake
#sed -i 's/--owner=0//'             kdevplatform/cmake/modules/KDevPlatformMacros.cmake
#sed -i 's/--group=0//'             kdevplatform/cmake/modules/KDevPlatformMacros.cmake

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTING=NO \
    -G Ninja

ninja -C build
ninja -C build install
