#!/bin/sh -e

export DESTDIR="$1"

sed -i 's/defined(__GLIBC__)/defined(__linux__)/' \
    src/framework/mlt_property.h

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DMOD_RTAUDIO=OFF \
    -DMOD_OPENCV=ON

cmake --build   build
cmake --install build
