#!/bin/sh -e

sed -i 's/defined(__GLIBC__)/defined(__linux__)/' \
    src/framework/mlt_property.h

./configure \
    --prefix=/usr \
    --enable-gpl \
    --enable-gpl3 \
    --enable-opengl \
    --enable-opencv \
    --disable-rtaudio

make
make DESTDIR="$1" install
