#!/bin/sh -e

export DESTDIR="$1"

rm -rf po

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTING=NO

cmake --build   build
cmake --install build
