#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < fix-glx.patch

rm -rf po

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTING=NO \
    -Wno-dev -G Ninja

ninja -C build
ninja -C build install
