#!/bin/sh -e

sed -i '/<type_traits>/a #include <limits>' \
    src/qmldebug/qqmlprofilerevent_p.h

# Without this folder, Qt can't find its own header files.
mkdir .git

qmake

make
make INSTALL_ROOT="$1" install
