#!/bin/sh -e

versions="4.1.2 4.2 4.3 4.4"

mkdir -p "$1/usr/share/xml/docbook/xml-dtd-4.5"
cp -af docbook.cat *.dtd ent/ *.mod "$1/usr/share/xml/docbook/xml-dtd-4.5/"
chmod 755 "$1/usr/share/xml/docbook/xml-dtd-4.5/ent"

# Create files, update catalogues
mkdir -p "$1/etc/xml"
export XML_CATALOG_FILES=""
xmlcatalog --noout --create "$1/etc/xml/docbook-xml"
xmlcatalog --noout --add \
	"public" \
	"-//OASIS//DTD DocBook XML V4.1.2//EN" \
	"http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd" \
	"$1/etc/xml/docbook-xml"

xmlcatalog --noout --add "public" \
	"-//OASIS//DTD DocBook XML CALS Table Model V4.1.2//EN" \
	"http://www.oasis-open.org/docbook/xml/4.1.2/calstblx.dtd" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//DTD DocBook XML CALS Table Model V4.1.2//EN" \
	"http://www.oasis-open.org/docbook/xml/4.1.2/calstblx.dtd" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//DTD XML Exchange Table Model 19990315//EN" \
	"http://www.oasis-open.org/docbook/xml/4.1.2/soextblx.dtd" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ELEMENTS DocBook XML Information Pool V4.1.2//EN" \
	"http://www.oasis-open.org/docbook/xml/4.1.2/dbpoolx.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ELEMENTS DocBook XML Document Hierarchy V4.1.2//EN" \
	"http://www.oasis-open.org/docbook/xml/4.1.2/dbhierx.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ENTITIES DocBook XML Additional General Entities V4.1.2//EN" \
	"http://www.oasis-open.org/docbook/xml/4.1.2/dbgenent.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ENTITIES DocBook XML Notations V4.1.2//EN" \
	"http://www.oasis-open.org/docbook/xml/4.1.2/dbnotnx.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ENTITIES DocBook XML Character Entities V4.1.2//EN" \
	"http://www.oasis-open.org/docbook/xml/4.1.2/dbcentx.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "rewriteSystem" \
	"http://www.oasis-open.org/docbook/xml/4.1.2" \
	"file:///usr/share/xml/docbook/xml-dtd-4.1.2" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "rewriteURI" \
	"http://www.oasis-open.org/docbook/xml/4.1.2" \
	"file:///usr/share/xml/docbook/xml-dtd-4.1.2" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//DTD DocBook XML V4.2//EN" \
	"http://www.oasis-open.org/docbook/xml/4.2/docbookx.dtd" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//DTD DocBook CALS Table Model V4.2//EN" \
	"http://www.oasis-open.org/docbook/xml/4.2/calstblx.dtd" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//DTD XML Exchange Table Model 19990315//EN" \
	"http://www.oasis-open.org/docbook/xml/4.2/soextblx.dtd" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ELEMENTS DocBook Information Pool V4.2//EN" \
	"http://www.oasis-open.org/docbook/xml/4.2/dbpoolx.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ELEMENTS DocBook Document Hierarchy V4.2//EN" \
	"http://www.oasis-open.org/docbook/xml/4.2/dbhierx.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ENTITIES DocBook Additional General Entities V4.2//EN" \
	"http://www.oasis-open.org/docbook/xml/4.2/dbgenent.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ENTITIES DocBook Notations V4.2//EN" \
	"http://www.oasis-open.org/docbook/xml/4.2/dbnotnx.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ENTITIES DocBook Character Entities V4.2//EN" \
	"http://www.oasis-open.org/docbook/xml/4.2/dbcentx.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "rewriteSystem" \
	"http://www.oasis-open.org/docbook/xml/4.2" \
	"file:///usr/share/xml/docbook/xml-dtd-4.2" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "rewriteURI" \
	"http://www.oasis-open.org/docbook/xml/4.2" \
	"file:///usr/share/xml/docbook/xml-dtd-4.2" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//DTD DocBook XML V4.3//EN" \
	"http://www.oasis-open.org/docbook/xml/4.3/docbookx.dtd" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//DTD DocBook CALS Table Model V4.3//EN" \
	"http://www.oasis-open.org/docbook/xml/4.3/calstblx.dtd" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//DTD XML Exchange Table Model 19990315//EN" \
	"http://www.oasis-open.org/docbook/xml/4.3/soextblx.dtd" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ELEMENTS DocBook Information Pool V4.3//EN" \
	"http://www.oasis-open.org/docbook/xml/4.3/dbpoolx.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ELEMENTS DocBook Document Hierarchy V4.3//EN" \
	"http://www.oasis-open.org/docbook/xml/4.3/dbhierx.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ENTITIES DocBook Additional General Entities V4.3//EN" \
	"http://www.oasis-open.org/docbook/xml/4.3/dbgenent.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ENTITIES DocBook Notations V4.3//EN" \
	"http://www.oasis-open.org/docbook/xml/4.3/dbnotnx.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ENTITIES DocBook Character Entities V4.3//EN" \
	"http://www.oasis-open.org/docbook/xml/4.3/dbcentx.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "rewriteSystem" \
	"http://www.oasis-open.org/docbook/xml/4.3" \
	"file:///usr/share/xml/docbook/xml-dtd-4.3" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "rewriteURI" \
	"http://www.oasis-open.org/docbook/xml/4.3" \
	"file:///usr/share/xml/docbook/xml-dtd-4.3" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//DTD DocBook XML V4.4//EN" \
	"http://www.oasis-open.org/docbook/xml/4.4/docbookx.dtd" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//DTD DocBook CALS Table Model V4.4//EN" \
	"http://www.oasis-open.org/docbook/xml/4.4/calstblx.dtd" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ELEMENTS DocBook XML HTML Tables V4.4//EN" \
	"http://www.oasis-open.org/docbook/xml/4.4/htmltblx.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//DTD XML Exchange Table Model 19990315//EN" \
	"http://www.oasis-open.org/docbook/xml/4.4/soextblx.dtd" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ELEMENTS DocBook Information Pool V4.4//EN" \
	"http://www.oasis-open.org/docbook/xml/4.4/dbpoolx.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ELEMENTS DocBook Document Hierarchy V4.4//EN" \
	"http://www.oasis-open.org/docbook/xml/4.4/dbhierx.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ENTITIES DocBook Additional General Entities V4.4//EN" \
	"http://www.oasis-open.org/docbook/xml/4.4/dbgenent.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ENTITIES DocBook Notations V4.4//EN" \
	"http://www.oasis-open.org/docbook/xml/4.4/dbnotnx.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ENTITIES DocBook Character Entities V4.4//EN" \
	"http://www.oasis-open.org/docbook/xml/4.4/dbcentx.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "rewriteSystem" \
	"http://www.oasis-open.org/docbook/xml/4.4" \
	"file:///usr/share/xml/docbook/xml-dtd-4.4" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "rewriteURI" \
	"http://www.oasis-open.org/docbook/xml/4.4" \
	"file:///usr/share/xml/docbook/xml-dtd-4.4" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//DTD DocBook XML V4.5//EN" \
	"http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//DTD DocBook XML CALS Table Model V4.5//EN" \
	"file:///usr/share/xml/docbook/xml-dtd-4.5/calstblx.dtd" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//DTD XML Exchange Table Model 19990315//EN" \
	"file:///usr/share/xml/docbook/xml-dtd-4.5/soextblx.dtd" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ELEMENTS DocBook XML Information Pool V4.5//EN" \
	"file:///usr/share/xml/docbook/xml-dtd-4.5/dbpoolx.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ELEMENTS DocBook XML Document Hierarchy V4.5//EN" \
	"file:///usr/share/xml/docbook/xml-dtd-4.5/dbhierx.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ELEMENTS DocBook XML HTML Tables V4.5//EN" \
	"file:///usr/share/xml/docbook/xml-dtd-4.5/htmltblx.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ENTITIES DocBook XML Notations V4.5//EN" \
	"file:///usr/share/xml/docbook/xml-dtd-4.5/dbnotnx.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ENTITIES DocBook XML Character Entities V4.5//EN" \
	"file:///usr/share/xml/docbook/xml-dtd-4.5/dbcentx.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "public" \
	"-//OASIS//ENTITIES DocBook XML Additional General Entities V4.5//EN" \
	"file:///usr/share/xml/docbook/xml-dtd-4.5/dbgenent.mod" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "rewriteSystem" \
	"http://www.oasis-open.org/docbook/xml/4.5" \
	"file:///usr/share/xml/docbook/xml-dtd-4.5" \
	"$1/etc/xml/docbook-xml"
xmlcatalog --noout --add "rewriteURI" \
	"http://www.oasis-open.org/docbook/xml/4.5" \
	"file:///usr/share/xml/docbook/xml-dtd-4.5" \
	"$1/etc/xml/docbook-xml"
