#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

rm -rf src/3rdparty/chromium/third_party/catapult
mv  -f catapult src/3rdparty/chromium/third_party/

# Without this folder, Qt can't find its header files.
mkdir .git src/3rdparty/chromium/.git

# Change the version string
sed -i 's/5.15.8/5.15.3/' .qmake.conf

# Fix musl include
sed -i '/inet.h>/a #include <sys/types.h>' \
    src/3rdparty/chromium/third_party/ots/include/opentype-sanitiser.h

sed -i '/errno.h>/a #include <string.h>' \
    src/3rdparty/chromium/mojo/public/cpp/platform/named_platform_channel_posix.cc

# The build fails if qtwebengine is already installed.
find . -name '*.pr[fio]' | while read -r file; do
    sed -i "s#INCLUDEPATH += #&\$\$QTWEBENGINE_ROOT/include #" "$file"
done

# Python 3.10.0
sed -i 's/from collections/from collections.abc/' \
    src/3rdparty/chromium/third_party/jinja2/tests.py

# Increase the limit -- thanks chromium
# shellcheck disable=2039,3045
ulimit -n 4096
#QMAKE_CXXFLAGS=-DQT_NO_ACCESSIBILITY
qmake -- \
    -feature-webengine-system-zlib \
    -feature-webengine-system-harfbuzz \
    -feature-webengine-system-png \
    -feature-webengine-system-libevent \
    -feature-webengine-system-libvpx \
    -feature-webengine-system-opus \
    -feature-webengine-system-libwebp \
    -feature-webengine-system-ffmpeg \
    -feature-webengine-proprietary-codecs \
    -no-feature-webengine-system-icu \
    -no-feature-webengine-system-glib

make
make INSTALL_ROOT="$1" install
