#!/bin/sh -e

mkdir build
cd build

# Somebody only checks for glibc
export CFLAGS="$CFLAGS -D_PR_POLL_AVAILABLE -D_PR_HAVE_OFF64_T -D_PR_INET6 -D_PR_HAVE_INET_NTOP -D_PR_HAVE_GETHOSTBYNAME2 -D_PR_HAVE_GETADDRINFO -D_PR_INET6_PROBE"

../nspr/configure \
    --prefix=/usr \
    --disable-debug \
    --enable-optimize \
    --enable-ipv6 \
    --enable-64bit

make CC="${CC:-gcc}" CXX="${CXX:-g++}"
make DESTDIR="$1" install

rm -f "$1/usr/lib/*.a"

cd config
install -Dm755 nspr-config "$1/usr/bin/nspr-config"
install -Dm644 nspr.pc     "$1/usr/lib/pkgconfig/nspr.pc"

rm -rf "$1/usr/bin/prerr.properties"
rm -rf "$1/usr/bin/compile-et.pl"
rm -rf "$1/usr/share/aclocal/nspr.m4"
rm -rf "$1/usr/include/nspr/md"
