#!/bin/sh -e

patch -p1 < nonrecursive-string-subst.patch

install -dm755 "$1/usr/share/xml/docbook/xsl-stylesheets-nons-$2"

cp -R VERSION assembly common eclipse epub epub3 extensions fo highlighting \
    html htmlhelp images javahelp lib manpages params profiling roundtrip \
    slides template tests tools webhelp website xhtml xhtml-1_1 xhtml5 \
"$1/usr/share/xml/docbook/xsl-stylesheets-nons-$2"

ln -s VERSION "$1/usr/share/xml/docbook/xsl-stylesheets-nons-$2/VERSION.xsl"

install -Dm644 README \
    "$1/usr/share/doc/docbook/xsl-nons-$2/README.txt"
install -Dm644 RELEASE-NOTES* NEWS* \
    "$1/usr/share/doc/docbook-xsl-nons-$2"
