#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < no-udev.patch

pkg-config --exists nss || {
    printf 'nss (or gnutls) is required\n'
    exit 1
}

# Remove intltool
sed -i "s/intltool_xml_cmd/['cp', '@INPUT@', '@OUTPUT@']/g" \
    data/meson.build
sed -i '/^intltool/d' \
    meson.build

kiss l elogind || logind=no
kiss l dhcpcd  || dhcpcd=false
kiss l gnutls  || crypto=nss
kiss l eiwd    || eiwd=false

meson \
    --prefix=/usr \
    --buildtype=release \
    -Dsession_tracking_consolekit=false \
    -Dsystemdsystemunitdir=no \
    -Dsystemd_journal=false \
    -Dintrospection=false \
    -Dmodify_system=true \
    -Dmodem_manager=false \
    -Dlibaudit=no \
    -Dselinux=false \
    -Dnmtui=false \
    -Dtests=no \
    -Dqt=false \
    -Dcrypto="${crypto:-gnutls}" \
    -Diwd="${eiwd:-true}" \
    -Ddhcpcd="${dhcpcd:-true}" \
    -Dresolvconf="${eiwd:-true}" \
    -Dsession_tracking="${logind:-elogind}" \
    . build

ninja -C build
ninja -C build install

install -Dm755 networkmanager.run  "$1/etc/sv/networkmanager/run"
install -Dm644 networkmanager.conf "$1/etc/NetworkManager/NetworkManager.conf"
