#!/bin/sh -e

export MSGFMT=/usr/bin/true
export MSGCAT=/usr/bin/true
export MSGMERGE=/usr/bin/true
export XGETTEXT=/usr/bin/true

sed -i 's/po src/po/g' Makefile.in
sed -i '/DENABLE_NLS/d' configure

./configure \
    --prefix=/usr \
    --witk-gtk-doc=no

make
make DESTDIR="$1" install
