#!/bin/sh -e

export MSGFMT=/usr/bin/true
export MSGCAT=/usr/bin/true
export MSGMERGE=/usr/bin/true
export XGETTEXT=/usr/bin/true

sed -i 's/po src/src/g' Makefile.in

./configure \
    --prefix=/usr \
    --with-gtk-doc=no

make
make DESTDIR="$1" install
