#!/bin/sh -e

for patch in *.patch; do 
    patch -p1 < "$patch"
done

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --disable-unit-tests \
    --enable-glx \
    --enable-dri \
    --enable-dri2 \
    --enable-dri3 \
    --enable-glamor \
    --enable-xorg \
    --enable-xwayland \
    --with-sha1=libcrypto

make
make DESTDIR="$1" install
