#!/bin/sh -e

export DESTDIR="$1"

rm -rf po

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTING=NO

cmake --build build
cmake --install build

install -Dm644 kde          "$1/etc/pam.d/kde"
install -Dm644 kde-np       "$1/etc/pam.d/kde-np"
install -Dm644 kscreensaver "$1/etc/pam.d/kscrensaver"
