#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

# Fix nasm hardcoded glibcism
sed -i '/CANONICALIZE_FILE_NAME/d' \
    src/3rdparty/chromium/third_party/nasm/config/config-linux.h

# Remove glibc header.
sed -i '/execinfo.h/d' \
    src/3rdparty/chromium/base/debug/stack_trace_posix.cc


# The build fails if qtwebengine is already installed.
find . -name '*.pr[fio]' | while read -r file; do
    sed -i "s#INCLUDEPATH += #&\$\$QTWEBENGINE_ROOT/include #" "$file"
done

qmake -- \
    -system-ninja \
    -system-zlib \
    -system-harfbuzz \
    -system-png \
    -system-libevent \
    -system-libvpx \
    -system-opus \
    -system-libwebp \
    -system-ffmpeg \
    -proprietary-codecs \
    -no-feature-webengine-system-icu \
    -no-feature-webengine-system-glib

make
make INSTALL_ROOT="$1" install
