#!/bin/sh -e

mv *.patch "$2/dmraid"
cd "$2/dmraid"

for patch in *.patch; do 
    patch -p1 < "$patch"
done

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --enable-shared_lib

# So this build system doesn't shit the bed
make -j1
make DESTDIR="$1" install

# It's all bad the whole way down
chmod 644 "$1/usr/include/dmraid/*"
chmod 644 "$1/usr/lib/libdrmraid.a"
