#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < $patch
done

# This is what happens when you require an entire browser
# to build your... privilege manager...
(
    cd autoconf2.13

    ./configure \
        --prefix="$PWD/../garbo" \
        --program-suffix=2.13

    make
    make install
)

export PATH="$PWD/garbo/bin:$PATH"

cd js/src
touch configure

# This is a crime against humanity
export SHELL=/bin/ash
PYTHON=/usr/bin/python2 ./configure \
    --prefix=/usr \
    --with-system-icu \
    --with-system-zlib \
    --with-system-nspr \
    --with-intl-api \
    --enable-ctypes \
    --enable-shared-js \
    --enable-readline \
    --enable-system-ffi \
    --disable-optimize \
    --disable-jemalloc \
    --enable-pie

make
make DESTDIR="$1" install
