#!/bin/sh -e

patch -p1 < no-fribidi.patch
patch -p1 < fix-firefox.patch

# Remove configure check for fribidi.
sed -i 's/fribidi >= 0\.19\.7//g' \
    configure

# Remove atk-bridge code.
sed -i 's/\(ATK_PACKAGES="atk\) atk-bridge-2.0"/\1"/' \
    configure
sed -i '/<atk-bridge.h>/d;/atk_bridge_adaptor_init/d' \
    gtk/a11y/gtkaccessibility.c

# Don't build GTK examples/demos/testsuite.
sed -i 's/demos tests testsuite examples//;s/docs \(m4macros\)/\1/' \
    Makefile.in

sh ./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --enable-wayland-backend \
    --enable-x11-backend \
    --disable-schemas-compile \
    --disable-cups \
    --disable-papi \
    --disable-cloudprint \
    --disable-glibtest \
    --disable-nls \
    --disable-installed-tests \
    --enable-introspection=no \
    --enable-colord=no \
    --enable-gtk-doc-html=no

make
make install

# GTK+3 on Wayland requires gsettings-desktop-schemas for gsettings to work
# correctly. Under X11 it made use of xsettings but this is no longer the case.
(
    cd schemas

    meson \
        --prefix=/usr \
        -Dintrospection=false \
        . output

    ninja -C output
    ninja -C output install
)

# We don't compile with librsvg which leads to this utility solely causing
# compiler errors for some packages. It has no use at all.
rm -f "$1/usr/bin/gtk-encode-symbolic-svg"

# Remove epoxy references from installed pkg-config files. The build system
# should have done this for us as it is statically linked.
for f in "$1/usr/lib/pkgconfig/"*.pc; do
    sed 's/epoxy >= 1.4//' "$f" > _
    mv -f _ "$f"
done

