#!/bin/sh -e

echo "polkitd:x:1998:" >> /etc/group
chown -R polkitd:polkitd "$1/etc/polkit-1/rules.d" "$1/usr/share/polkit-1/rules.d"
chmod -R 700 "1/etc/polkit-1/rules.d" "$1/usr/share/polkit-1/rules.d"
chmod 4755 "$1/usr/lib/polkit-1/polkit-agent-helper-1"
chmod 4755 "$1/usr/bin/pkexec"
