#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DLIBICAL_BUILD_TESTING=false \
    -DGOBJECT_INTROSPECTION=false \
    -DICAL_BUILD_DOCS=false \
    -DSHARED_ONLY=true \
    -DICAL_GLIB=false \
    -Wno-dev -G Ninja

ninja -C build
ninja -C build install
