#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DENABLE_GTK_DOC=false \
    -DSHARED_ONLY=true \
    -Wno-dev -G Ninja

ninja -C build
ninja -C build install
