#!/bin/sh -e

# Somebody wrote a test that only cares about glibc
# tsk tsk tsk
export CFLAGS="$CFLAGS -D_PR_POLL_AVAILABLE -D_PR_HAVE_OFF64T -D_PR_HAVE_INET6 -D_PR_HAVE_INET_NTOP -D_PR_HAVE_GETHOSTBYNAME2 -D_PR_HAVE_GETADDRINFO -D_PR_INET6_PROBE"

for patch in *.patch; do
    patch -p1 < $patch
done

mkdir build
cd build
../nspr/configure \
    --prefix=/usr \
    --disable-debug \
    --enable-optimize \
    --enable-ipv6 \
    --enable-64bit

make CC="${CC:-gcc}" CXX="${CXX:-g++}"
make DESTDIR="$1" install

rm -f usr/lib/*.a

cd config
install -Dm755 nspr-config "$1/usr/bin/nspr-config"
install -Dm644 nspr.pc     "$1/usr/lib/pkgconfig/nspr.pc"

rm -rf "$1/usr/bin/prerr.properties" \
       "$1/usr/bin/compile-et.pl" \
       "$1/usr/share/aclocal/nspr.m4" \
       "$1/usr/include/nspr/md"
