#!/bin/sh -e

export CFLAGS="$CFLAGS -O3 -fomit-frame-pointer -ffast-math"
export CFLAGS="$CFLAGS -fstrict-aliasing -malign-double"

(
    cd fftw-quad

    ./configure \
        --prefix=/usr \
        --enable-shared \
        --enable-threads \
        --enable-openmp \
        --enable-quad-precision
)

(
    cd fftw-single

    ./configure \
        --prefix=/usr \
        --enable-shared \
        --enable-threads \
        --enable-openmp \
        --enable-sse2 \
        --enable-avx \
        --enable-single
)
    
(
    cd fftw-double
    
    ./configure \
        --prefix=/usr \
        --enable-shared \
        --enable-threads \
        --enable-openmp \
        --enable-sse2 \
        --enable-avx
)

(
    cd fftw-long-double
    
    ./configure \
        --prefix=/usr \
        --enable-shared \
        --enable-threads \
        --enable-openmp \
        --enable-long-double
)

make -C fftw-quad
make -C fftw-single
make -C fftw-double
make -C fftw-long-double
make DESTDIR="$1" install -C fftw-quad
make DESTDIR="$1" install -C fftw-single
make DESTDIR="$1" install -C fftw-double
make DESTDIR="$1" install -C fftw-long-double
