#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < fix-build.patch

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DENABLE_JOURNALD=OFF \
    -DNO_SYSTEMD=ON \
    -DUSE_ELOGIND=ON \
    -DUID_MIN=500 \
    -DUID_MAX=65000 \
    -Wno-dev -G Ninja

ninja -C build
ninja -C build install

install -Dm755 sddm.run "$1/etc/sv/sddm/run"
