#!/bin/sh -e

export DESTDIR="$1" 

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTING=NO \
    -Wno-dev -G Ninja

ninja -C build
ninja -C build install

# Fix building with gcc 11.1.0
# Fixed in next release!
sed -i '/<array>/a <limits>' "$1/usr/include/Vc/common/simdarray.h"
