#!/bin/sh -e

# Without this folder, Qt can't find its own header files.
mkdir .git

qmake

make
make INSTALL_ROOT="$1" install

find "$1/usr/lib" -type f -name '*.prl' \
    -exec sed -i -e '/^QMAKE_PRL_BUILD_DIR/d' {} \;
