#!/bin/sh -e

export DESTDIR="$1"

meson \
    --libdir=/usr/lib \
    --libexecdir=/usr/libexec \
    --buildtype=plain \
    -Dprefix=/usr \
    -Dcgroup-controller=elogind \
    -Dhalt-path=/usr/bin/halt \
    -Dreboot-path=/usr/bin/reboot \
    -Ddefault-hierarchy=hybrid \
    -Ddefault-kill-user-processes=false \
    -Dpolkit=true \
    . output

ninja -C output
ninja -C output install

ln -s libelogind.pc            "$1/usr/lib/pkgconfig/libsystemd.pc"
ln -s libelogind.pc            "$1/usr/lib/pkgconfig/libsystemd-logind.pc"
ln -s "$1/usr/include/elogind" "$1/usr/include/systemd"

install -Dm755 elogind.run "$1/etc/sv/elogind/run"
