#!/bin/sh -e

meson \
    --buildtype=plain \
    -Dprefix=/usr \
    -Dcgroup-controller=elogind \
    -Dbuspolicydir=/etc/dbus-1/system.d \
    -Drootlibexecdir=/usr/libexec/elogind \
    -Dreboot-path=/usr/bin/reboot \
    -Ddefault-kill-user-processes=false \
    -Dpolkit=true \
    build

ninja -C build
DESTDIR="$1" ninja -C build install

ln -s libelogind.pc            "$1/usr/lib/pkgconfig/libsystemd.pc"
ln -s libelogind.pc            "$1/usr/lib/pkgconfig/libsystemd-logind.pc"
ln -s "$1/usr/include/elogind" "$1/usr/include/systemd"

install -Dm755 elogind.run "$1/etc/sv/elogind/run"
