#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

# Insecure module
sed -i 's/pam_rhosts//g'   modules/Makefile.am

# For some reason they are syntactically busted
sed -i 's/pam_setquota//g' modules/Makefile.am
sed -i 's/pam_usertype//g' modules/Makefile.am

# Otherwise 'non required' enters our build system
export ac_cv_search_crypt=no

# Because we patch *.am, we have to regenerate stuff
# autoreconf calls autopoint, which is a gettext thing.
# So we just call the bits we need.

aclocal --force -I m4
autoconf -f
autoheader -f
automake -af

./configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --sbindir=/usr/bin \
    --disable-nls \
    --disable-db

make
make DESTDIR="$1" install

# Let's install our pam files to get us started with authenticating!
install -Dm644 su.pamd                          "$1/etc/pam.d/su"
install -Dm644 other.pamd                       "$1/etc/pam.d/other"
install -Dm644 base-auth.pamd                   "$1/etc/pam.d/base-auth"
install -Dm644 base-account.pamd                "$1/etc/pam.d/base-account"
install -Dm644 base-session.pamd                "$1/etc/pam.d/base-session"
install -Dm644 base-password.pamd               "$1/etc/pam.d/base-password"
install -Dm644 system-login.pamd                "$1/etc/pam.d/system-login"
install -Dm644 system-local-login.pamd          "$1/etc/pam.d/system-local-login"
install -Dm644 base-session-noninteractive.pamd "$1/etc/pam.d/base-session-noninteractive"
