#!/bin/sh -e

export MSGFMT=/usr/bin/true
export MSGMERGE=/usr/bin/true
export XGETTEXT=/usr/bin/true

patch -p1 < remove-gettext.patch

./configure \
    --prefix=/usr

make
make DESTDIR="$1" install
