#!/bin/sh -e

# Just a poor system.
sed -i "s/GIT_VERSION/[$2]/" configure.ac
touch version.m4
autoreconf -sfi

./configure \
    --prefix=/usr \
    --disable-docs \
    --without-bash \
    --without-systemd

make
make DESTDIR="$1" install
