#!/bin/sh -e

export DESTDIR="$1"

# Busybox grep supports quiet, just not the long option.
sed -i 's/grep --quiet/grep -q/g' generate-24px-versions.sh

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTING=NO \
    -Wno-dev -G Ninja

ninja -C build
ninja -C build install
