#!/bin/sh -e

sed -i '/#include <sys\/stat.h>/a #define __USE_GNU/' \
    src/udiskslinuxblock.c

./configure \
    --prefix=/usr \
    --enable-lvm2 \
    --enable-lvmcache \
    --enable-zram \
    --disable-gtk-doc-html \
    --disable-man \
    --disable-nls

make
make DESTDIR="$1" install
