#!/bin/sh -e

export CARGO_HOME=$PWD

(
    cd vendor

    for crate in *.crate; do
        tar xf "$crate"

        # Strip the filename from the sha256sum output.
        sha256=$(sha256sum "$crate")
        sha256=${sha256%% *}

        printf '{"package":"%s","files":{}}\n' "$sha256" \
            > "${crate%.crate}/.cargo-checksum.json"
    done
)

mkdir -p .cargo

cat > .cargo/config << EOF
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
EOF

cargo build \
    --release \
    --frozen

install -Dm755 -ogreetd -ggreetd target/release/tuigreet "$1/usr/bin/tuigreet"
