#!/bin/sh -e

cd musl-fts-1.2.7

autoreconf -sfi

export CFLAGS="$CFLAGS -fPIC" 

./configure \
    --prefix=/usr

make
make DESTDIR="$1" install

install -Dm644 musl-fts.pc "$1/usr/lib/pkgconfig/libfts.pc"
