#!/bin/sh -e

mv nls.m4 buildutil/nls.m4
mv intltool.m4 buildutil/intltool.m4
mv introspection.m4 buildutil/introspection.m4

for patch in *.patch; do
    patch -p1 < $patch
done

autoreconf -sfi

export MSGFMT=/usr/bin/true
export MSGMERGE=/usr/bin/true
export XGETTEXT=/usr/bin/true
export INTLTOOL_MERGE=/usr/bin/true
export INTLTOOL_UPDATE=/usr/bin/true
export INTLTOOL_EXTRACT=/usr/bin/true

patch -p1 < remove-intltool.oops

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-gtk-doc-html \
    --disable-man-pages \
    --disable-examples \
    --disable-nls \
    --disable-static \
    --disable-systemd \
    --enable-test=no \
    --enable-introspection=no \
    --enable-libsystemd-login=no \
    --enable-libelogind=no \
    --with-backend=keyfile \
    --with-authfw=shadow \
    --with-os-type=KISS

# We can try experimenting with not using pam and instead using shadow...
    #--with-authfw=pam \

make
make DESTDIR="$1" install

install -Dm755 polkit.run "$1/etc/sv/polkitd/run"
