#!/bin/sh -e

kiss l linux-pam || kiss l shadow || {
    printf 'linux-pam or shadow is required\n'
    exit 1
}

for patch in *.patch; do
    patch -p1 < $patch
done

# The patches that we're using to add a keyfile backend to drop mozjs require
# that we regenerate our build scripts! So we do that here. Because polkit
# upstream believes that we already have gobject, intltool, etc. installed (even
# though they're optional), we have to include their macros in buildutil/*.m4 so
# that autotools do their job correctly. Otherwise, our configure script will
# generate with syntax errors.
autoreconf -sfi

# We still have to pass these even if we disable nls. So why make it a
# configure-time option? ¯\_(!_!)_/¯
export MSGFMT=/usr/bin/true
export MSGMERGE=/usr/bin/true
export XGETTEXT=/usr/bin/true
export INTLTOOL_MERGE=/usr/bin/true
export INTLTOOL_UPDATE=/usr/bin/true
export INTLTOOL_EXTRACT=/usr/bin/true

# Even WITH NLS disabled, AND skipping the aforementioned checks, configure
# still will error if we do not have a perl XML::Parser & INTLTOOL > 0.40.0.
# And because I find this very frustrating, I've decided to brutalize their
# script instead of just using simple seds to change the checks. Maybe one day I
# will no longer be so petty. Until then, oops.
patch -p1 < remove-intltool.oops

# sddm requires elogind. Instead of maintaining a separate polkit like so many
# other distrubtions, we will simply imsert a pkgconf check to determine whether
# or not to include libelogind support.

pkg-config --exists libelogind || libelogind=no
kiss l linux-pam || auth=shadow

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-gtk-doc-html \
    --disable-man-pages \
    --disable-examples \
    --disable-nls \
    --disable-static \
    --disable-systemd \
    --enable-test=no \
    --enable-introspection=no \
    --enable-libsystemd-login=no \
    --enable-libelogind="${libelogind:-yes}" \
    --with-backend=keyfile \
    --with-authfw="${auth:-pam}" \
    --with-os-type=KISS

make
make DESTDIR="$1" install

install -Dm755 polkit.run "$1/etc/sv/polkitd/run"

if kiss l linux-pam; then
    install -Dm644 polkit.pam "$1/etc/pam.d/polkit-1"
fi
