#!/bin/sh -e

patch -p1 < build-fix.patch

export DESTDIR="$1"

CFLAGS= make -C xdgmime

find . -type f -name meson.build -exec \
    sed -i "/subdir('tests')/d" {} +

meson \
    --prefix=/usr \
    -Dupdate-mimedb=false \
    -Dxdgmime-path="$PWD/xdgmime" \
    . build

ninja -C build
ninja -C build install
