#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < $patch
done

# Who needs intltool anyways?
sed -i '/INTLTOOL_APPLIED_VERSION=/s:=.*:=0.40.0:' configure
sed -i -e '/XML::Parser perl module is required for intltool/s|^|:|' configure

export INTLTOOL_EXTRACT=/usr/bin/true
export INTLTOOL_MERGE=/usr/bin/true
export INTLTOOL_UPDATE=/usr/bin/true
export MSGFMT=/usr/bin/true
export MSGMERGE=/usr/bin/true
export XGETTEXT=/usr/bin/true

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --with-authfw=pam \
    --with-os-type=KISS \
    --disable-static \
    --disable-gtk-doc-html \
    --disable-systemd \
    --disable-man-pages \
    --disable-nls \
    --enable-libsystemd-login=no \
    --enable-libelogind=yes

make
make DESTDIR="$1" install

install -Dm755 polkit.run "$1/etc/sv/polkitd/run"
