#!/bin/sh -e

cat >> << EOF

We may want to give polkitd a group and a user.
addgroup -S polkitd 2>/dev/null
adduser -S -D -H -h /var/empty -s /sbin/nologin -G polkitd -g polkitd polkitd 2>/dev/null
EOF
