#!/bin/sh -e

export DESTDIR="$1"

sed -i '/#include <QJSValue>/a #include <QDebug>'   src/colorutils.h
sed -i '/#include <QQuickItem>/a #include <QColor>' src/shadowedrectangle.h

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTING=NO \
    -Wno-dev -G Ninja

ninja -C build
ninja -C build install
