#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < include.patch

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTING=NO \ 
    -Wno-dev

cmake --build   build
cmake --install build
