#!/bin/sh -e

sed -i '/#include <config.h>/a #include <sched.h>' \
    src/benchmark.c
sed -i '/#include <config.h>/a #define _GNU_SOURCE' \
    src/benchmark.c

./configure \
    --prefix=/usr \
    --without-doxygen

make
make DESTDIR="$1" install
