#!/bin/sh -e

sed -i 's/PERMISSIONS OWNDER_READ//' CMake/utility.cmake

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_UNIT_TESTS=False \
    -DBUILD_EXAMPLES=OFF \
    -Wno-dev

cmake --build   build
cmake --install build

# Incorrect permissions set at build-time
find "$1/usr/include/rttr" -type f -exec chmod 644 {} \;
